# 11 — Pandas Basics - Part 1

**Before you start:**

- Give each concrete step in the process its own cell. If you cannot describe what a cell does in a short phrase ("load the text file," "strip punctuation," "count word frequency"), it is probably two steps — split it into two cells.
- Add a Markdown cell above each code cell explaining what you're about to do and *why* — write the explanation **before** you write the code. This forces you to say what you expect to happen before you find out what actually happens. Here is a <a href="Markdown-Cheatsheet.html" target="_blank">**CHEAT SHEET**</a> for Markdown codes. Here is an even more <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">**COMPLETE CHEAT SHEET**</a>
- Use `#` comments inside code cells for line-level notes (why a line is written a certain way, what a tricky argument does, reminders to yourself. **Remember the 6-month rule** - You want to be able to know what is going on in your code if you were to open it 6 months from now.
- Log anything that breaks in the **Failure Log** at the bottom of this notebook — even if you never fixed it. Note the error message and what you tried.

Rename this file using the format `Unnamed-##-UnitTopic-Notebook.ipynb` before you begin (e.g. `Proctor-02-Python-Basics-Notebook.ipynb`).
You can accomplish this either by making a copy of the file in your Finder or File Explorer and renaming it there. Or, you can do it after you open Jupyter Notebooks using the folder navigation there. Be warned: Notebooks to not like a double click!

## Imports

Run this cell once, at the start of your session. Add every `import` statement for this notebook here — you shouldn't need to re-run this as you work through the rest of the notebook.

In [23]:
import pandas as pd

---

## Your Work

Build your notebook below, one concrete step at a time. For each step:

1. Add a Markdown cell describing what you're about to do and why.
2. Add a code cell that does it.
3. Run it, check the output, and add `#` comments for anything worth remembering about that line.

Repeat for as many steps as the chapter/unit walks through — including if it introduces a new dataset, a new function, or a new example partway through. Don't feel like you need to force everything into a single sequence if the material doesn't.

### Code Workthrough

Sets the maximum number of rows Pandas can display to 100.

In [24]:
pd.options.display.max_rows = 100

Uses Pandas to read the CSV file containing Bellevue almshouse data and stores it in a DataFrame called bellevue_df.

In [25]:
bellevue_df = pd.read_csv('../data/bellevue_almshouse_modified.csv', delimiter=",")

Displays the bellevue_df DataFrame and shows the information from the file in a table.

In [26]:
bellevue_df

,date_in,first_name,last_name,age,disease,profession,gender,children
0,1847-04-17,Mary,Gallagher,28.0,recent emigrant,married,w,Child Alana 10 days
1,1847-04-08,John,Sanin (?),19.0,recent emigrant,laborer,m,Catherine 2 mo
2,1847-04-17,Anthony,Clark,60.0,recent emigrant,laborer,m,Charles Riley afed 10 days
3,1847-04-08,Lawrence,Feeney,32.0,recent emigrant,laborer,m,Child
4,1847-04-13,Henry,Joyce,21.0,recent emigrant,NaN,m,Child 1 mo
...,...,...,...,...,...,...,...,...
9579,1847-06-17,Mary,Smith,47.0,NaN,NaN,w,NaN
9580,1847-06-22,Francis,Riley,29.0,lame,superintendent,m,NaN
9581,1847-07-02,Martin,Dunn,4.0,NaN,NaN,m,NaN
9582,1847-07-08,Elizabeth,Post,32.0,NaN,NaN,w,NaN
9583,1847-04-28,Bridget,Ryan,28.0,destitution,spinster,w,NaN

Displays the first 2 rows of the bellevue_df DataFrame.

In [27]:
bellevue_df.head(2)

,date_in,first_name,last_name,age,disease,profession,gender,children
0,1847-04-17,Mary,Gallagher,28.0,recent emigrant,married,w,Child Alana 10 days
1,1847-04-08,John,Sanin (?),19.0,recent emigrant,laborer,m,Catherine 2 mo

Displays the first 10 rows of the bellevue_df DataFrame.

In [28]:
bellevue_df.head(10)

,date_in,first_name,last_name,age,disease,profession,gender,children
0,1847-04-17,Mary,Gallagher,28.0,recent emigrant,married,w,Child Alana 10 days
1,1847-04-08,John,Sanin (?),19.0,recent emigrant,laborer,m,Catherine 2 mo
2,1847-04-17,Anthony,Clark,60.0,recent emigrant,laborer,m,Charles Riley afed 10 days
3,1847-04-08,Lawrence,Feeney,32.0,recent emigrant,laborer,m,Child
4,1847-04-13,Henry,Joyce,21.0,recent emigrant,NaN,m,Child 1 mo
5,1847-04-14,Bridget,Hart,20.0,recent emigrant,spinster,w,Child
6,1847-04-14,Mary,Green,40.0,recent emigrant,spinster,w,And child 2 months
7,1847-04-19,Daniel,Loftus,27.0,destitution,laborer,m,NaN
8,1847-04-10,James,Day,35.0,recent emigrant,laborer,m,NaN
9,1847-04-10,Margaret,Farrell,30.0,recent emigrant,widow,w,NaN

Displays 10 randomly selected rows from the bellevue_df DataFrame.

In [29]:
bellevue_df.sample(10)

,date_in,first_name,last_name,age,disease,profession,gender,children
2488,1846-01-21,Ann,Foley,31.0,NaN,married,w,NaN
6266,1847-08-06,William,Lanahan,24.0,sickness,printer,m,NaN
1794,1847-05-19,Reynolds,McDonnell,25.0,recent emigrant,laborer,m,NaN
2666,1846-03-03,Ann,Clifford,28.0,NaN,married,w,NaN
370,1847-05-04,John,Fischer,30.0,sickness,weaver,m,NaN
633,1847-06-04,John,McAsdo,35.0,recent emigrant,laborer,m,NaN
5204,1847-02-24,William,Morrison,50.0,sickness,machinist,m,NaN
485,1847-05-18,John,Carroll,30.0,recent emigrant,laborer,m,NaN
6553,1847-08-27,David,Cope,35.0,sickness,laborer,m,NaN
538,1847-05-22,James,English,4.0,recent emigrant,laborer,m,NaN

Displays important information about all the columns in the bellevue_df DataFrame.

In [30]:
bellevue_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9584 entries, 0 to 9583
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date_in     9584 non-null   str
 1   first_name  9580 non-null   str
 2   last_name   9584 non-null   str
 3   age         9534 non-null   float64
 4   disease     6497 non-null   str
 5   profession  8565 non-null   str
 6   gender      9584 non-null   str
 7   children    37 non-null     str
dtypes: float64(1), str(7)
memory usage: 944.6 KB

Calculates and displays summary statistics for columns in the bellevue_df DataFrame containing numerical data.

In [31]:
bellevue_df.describe()

               age
count  9534.000000
mean     30.332604
std      14.179608
min       0.080000
25%      21.000000
50%      28.000000
75%      39.000000
max      97.000000

Calculates and displays summary statistics for all columns in the bellevue_df DataFrame, not just the columns with numerical data.

In [32]:
bellevue_df.describe(include='all')

,date_in,first_name,last_name,age,disease,profession,gender,children
count,9584,9580,9584,9534.000000,6497,8565,9584,37
unique,653,523,3142,NaN,75,172,5,36
top,1847-05-24,Mary,Kelly,NaN,sickness,laborer,m,Child
freq,113,979,137,NaN,2706,3108,4958,2
mean,NaN,NaN,NaN,30.332604,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,14.179608,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,0.080000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,21.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,28.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,97.000000,NaN,NaN,NaN,NaN

Selects the column "disease" from the bellevue_df DataFrame.

In [33]:
bellevue_df['disease']

0       recent emigrant
1       recent emigrant
2       recent emigrant
3       recent emigrant
4       recent emigrant
             ...
9579                NaN
9580               lame
9581                NaN
9582                NaN
9583        destitution
Name: disease, Length: 9584, dtype: str

---

## Failure Log

Note anything that broke, any error message you didn't understand, and what you tried — even if it didn't work. You don't need to have fixed it.

- 
- 
-